services:
  insanely-fast-whisper:
    build:
      context: .
      dockerfile: Dockerfile

    image: ghrc.io/beecave-homelab/insanely-fast-whisper-rocm:rocm6.1
    container_name: insanely-fast-whisper-rocm
    restart: unless-stopped

    devices:
      - "/dev/kfd:/dev/kfd"
      - "/dev/dri:/dev/dri"
    stdin_open: true
    tty: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    group_add:
      - video
    ipc: host
    shm_size: 8G

    command: ["/bin/bash", "entrypoint.sh"]

    ports:
      - 7860:7860
    
    volumes:
      - "./uploads:/app/uploads"
      - "./transcripts:/app/transcripts"
      - "./models:/app/models"
      - "./testing:/app/testing"