services:
  insanely-fast-whisper:
    build:
      context: .
      dockerfile: Dockerfile

    # image: ghrc.io/beecave-homelab/insanely-fast-whisper-rocm:main
    image: beecave/insanely-fast-whisper-rocm:main
    container_name: insanely-fast-whisper-rocm
    restart: unless-stopped

    devices:
      - "/dev/kfd:/dev/kfd"
      - "/dev/dri:/dev/dri"
    stdin_open: true
    tty: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    group_add:
      - video
    ipc: host
    shm_size: 8G

    env_file:
      - .env

    ports:
      - 7861:7860
    
    volumes:
      - "./uploads:/app/uploads"
      - "./transcripts:/app/transcripts"
      - "./logs:/app/logs"

    # Choose one of the commands below
    # command: ["app.py"] # For a simple Gradio webui for uploading files.
    command: ["main.py"] # For automatically processing any file placed in the ./uploads directory.
    # command: ["convert_output.py"] # insanely-fast-whisper creates .json files. Convert them to .txt and .srt file with this script.