services:
  insanely-fast-whisper:
    build:
      context: .
      dockerfile: Dockerfile

    # image: ghrc.io/beecave-homelab/insanely-fast-whisper-rocm:main
    image: beecave/insanely-fast-whisper-rocm:main
    container_name: insanely-fast-whisper-rocm
    restart: unless-stopped

    # To allow AMD GPU access:
    devices:
      - "/dev/kfd:/dev/kfd"
      - "/dev/dri:/dev/dri"
    stdin_open: true
    tty: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    group_add:
      - video
    ipc: host
    shm_size: 8G

    env_file:
      - .env

    ports:
      - 7862:7860
    
    volumes:
      - "./uploads:/app/uploads"
      - "./transcripts:/app/transcripts"
      - "./transcripts-srt:/app/transcripts-srt"
      - "./transcripts-txt:/app/transcripts-txt"
      - "./logs:/app/logs"
      - "./src:/app/src"
      - "./testing:/app/testing"

    # Choose one of the commands below
    # - ["src/app.py"] # For a simple Gradio webui for uploading files.
    # - ["src/main.py"] # For automatically processing any file placed in the ./uploads directory.
    # - ["src/convert_output.py"] # insanely-fast-whisper creates .json files. Convert them to .txt and .srt file with this script.
    # - ["testing/test_cuda.py"] # Test CUDA availability.

    command: ["src/main.py"] # For automatically processing any file placed in the ./uploads directory.